Rework on docker-images
librecores/docker-images pull request #20
Opened 2019-06-17 17:57 UTC by Nancy-Chauhan

Solves #19 #18

2019-06-18 14:03 UTC, oleg-nenashev commented on librecores-ci-riscv/Dockerfile
> +FROM librecores/librecores-ci:latest
pin the release version maybe? We will suffer from race conditions if we keep latest here

2019-06-18 14:05 UTC, oleg-nenashev requested changes
With the current version the build will not be reproducible. I suggest pinning all versions instead of relying on `latest`

2019-06-18 14:05 UTC, oleg-nenashev commented on librecores-ci-openrisc/Dockerfile
> +git clone https://github.com/openrisc/or1k-tests.git ; &&\
It picks latest from the repository and makes the build not reproducible. I suggest pinning a commit ID or a tag

2019-06-18 14:05 UTC, oleg-nenashev commented on librecores-ci-openrisc/Dockerfile
> +  https://github.com/stffrdhrn/gcc/releases/download/or1k-9.0.0-20181113/or1k-elf-9.0.0-20181112.tar.xz
Move version to a constant / `ARG` ?

2019-06-19 21:47 UTC, oleg-nenashev approved these changes
Fine with me. Is it still a draft? Or should I merge it and see whether it works on DockerHib?

2019-06-20 07:24 UTC, oleg-nenashev commented on librecores-ci-openrisc/Dockerfile
> +RUN apt-get update && apt-get install -y curl
This part can be optimized to reduce number and size of layers, see LCCI

2019-07-08 20:12 UTC, Nancy-Chauhan commented
@oleg-nenashev This should work now.

2019-07-09 08:54 UTC, stffrdhrn commented
This looks nice to have all the tools installed

2019-07-11 07:15 UTC, oleg-nenashev approved these changes
Would be nice to have some documentation, but we can do it later

2019-07-11 07:16 UTC, merged

2019-07-22 07:02 UTC, oleg-nenashev commented
The PR was amended in #25