WIP : Update docker-images to the recent versions of FuseSOC and tools.
librecores/docker-images pull request #6
Opened 2019-01-28 11:45 UTC by Nancy-Chauhan

**This is Work in progress to solve the issue :** 

librecores/librecores-ci/issues/49.

**Work Left** : 

Update LibreCores Pipeline Library so that we run demos with recent versions of the tools.

2019-01-28 13:11 UTC, oleg-nenashev requested changes
Likely cocotb won't work after the change

2019-01-28 13:11 UTC, oleg-nenashev commented on librecores-ci-modules-fpga/Dockerfile
> +WORKDIR /cocotb
Env var below is still the same: "ENV COCOTB=/tmp/cocotb"

2019-01-28 13:11 UTC, oleg-nenashev commented on librecores-ci-modules/Dockerfile
> +WORKDIR /cocotb
same

2019-05-24 08:31 UTC, Nancy-Chauhan commented
@oleg-nenashev Updated LibreCores CI Docker images to newer tool versions

2019-05-24 12:28 UTC, oleg-nenashev approved these changes
Has it been tested?

2019-05-24 15:39 UTC, Nancy-Chauhan commented
@oleg-nenashev  Yes, I checked on a local machine.

2019-05-26 11:18 UTC, merged

2019-05-27 07:24 UTC, oleg-nenashev commented
Update: it was not a change for mor1kx flow support